export const NETWORK_WARNING_SHOW = 'NETWORK_WARNING_SHOW'
export const NETWORK_WARNING_SHOW_CONTACT = 'NETWORK_WARNING_SHOW_CONTACT'

export const APPSTATUS_GET_START = 'APPSTATUS_GET_START'
export const APPSTATUS_GET_DONE = 'APPSTATUS_GET_DONE'

export const UPDATECONTACT_POST_START = 'UPDATECONTACT_POST_START'
export const UPDATECONTACT_POST_DONE = 'UPDATECONTACT_POST_DONE'

export const INSTALL_GET_START = 'INSTALL_GET_START'
export const INSTALL_GET_DONE = 'INSTALL_GET_DONE'

export const UPDATE_POST_START = 'UPDATE_POST_START'
export const UPDATE_POST_DONE = 'UPDATE_POST_DONE'

export const RCSITEKEY_CHANGE = 'RCSITEKEY_CHANGE'
export const RCSITESECRET_CHANGE = 'RCSITESECRET_CHANGE'

export const ERROR_DISMISS = 'ERROR_DISMISS'
export const SUCCESS_DISMISS = 'SUCCESS_DISMISS'

export const CONTACT_ERROR_DISMISS = 'CONTACT_ERROR_DISMISS'
export const CONTACT_SUCCESS_DISMISS = 'CONTACT_SUCCESS_DISMISS'
export const CHANGE_CONTACT = 'CHANGE_CONTACT'
export const RANGE_SLIDER_CHANGE = 'RANGE_SLIDER_CHANGE'
// Indicates the start of fetching reCAPTCHA settings.
export const GET_RECAPTCHA_SETTINGS_START = 'GET_RECAPTCHA_SETTINGS_START'
// Indicates the successful fetching of reCAPTCHA settings.
export const GET_RECAPTCHA_SETTINGS_SUCCESS = 'GET_RECAPTCHA_SETTINGS_SUCCESS'
// Indicates the failure to fetch reCAPTCHA settings.
export const GET_RECAPTCHA_SETTINGS_FAILURE = 'GET_RECAPTCHA_SETTINGS_FAILURE'
// Indicates the start of updating reCAPTCHA settings.
export const UPDATE_RECAPTCHA_SETTINGS_START = 'UPDATE_RECAPTCHA_SETTINGS_START'
// Indicates the successful updating of reCAPTCHA settings.
export const UPDATE_RECAPTCHA_SETTINGS_SUCCESS = 'UPDATE_RECAPTCHA_SETTINGS_SUCCESS'
// Indicates the failure to update reCAPTCHA settings.
export const UPDATE_RECAPTCHA_SETTINGS_FAILURE = 'UPDATE_RECAPTCHA_SETTINGS_FAILURE'
export const RECAPTCHA_TYPE_CHANGE = 'RECAPTCHA_TYPE_CHANGE'
